### ISSUE TITLE
NotFound: Page not found

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-infra/evergreen#382]
When I launch the evergreen, but cannot visit http://localhost:12345/evergreen. Error logs below:

command is docker run --name evergreen --restart=always -ti -p 12345:80 -v /var/run/docker.sock:/var/run/docker.sock jenkins/evergreen:docker-cloud

NotFound: Page not found
    at new NotFound (/evergreen/client/node_modules/@feathersjs/errors/lib/index.js:114:17)
    at /evergreen/client/node_modules/@feathersjs/errors/lib/not-found-handler.js:7:10
    at Layer.handle [as handle_request] (/evergreen/client/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/evergreen/client/node_modules/express/lib/router/index.js:317:13)
    at /evergreen/client/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/evergreen/client/node_modules/express/lib/router/index.js:335:12)
    at next (/evergreen/client/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/evergreen/client/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:182:13)
    at SendStream.error (/evergreen/client/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/evergreen/client/node_modules/send/index.js:421:12)
    at next (/evergreen/client/node_modules/send/index.js:736:16)
    at onstat (/evergreen/client/node_modules/send/index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:154:21)

**Comment by batmat** [comment]
Can you try without the final /evergreen in your URL?

That still shouldn't trigger an error, but trying to understand. (Will check later, on the phone currently). Thanks!

**Comment by LinuxSuRen** [comment]
It's ok without /evergreen.

**Comment by batmat** [comment]
@LinuxSuRen IIUC, your problem is solved. So I am going to close this issue. Please reopen or comment here if I misunderstood.

Thanks!
